import { Request, Response } from 'express';
import { NotificationTemplateService } from '../services/notificationTemplate.service';
import { AcademicPerformanceService } from '../services/academicPerformance.service';
import { prisma } from '../db';
import { NotificationCategory } from '@prisma/client';

import { NotificationService } from '../services/notification.service';

export class NotificationTemplateController {
  /**
   * POST /api/admin/notifications/preview-template
   * Previews message text generated by NotificationTemplateService based on category and parameters.
   */
  static async previewTemplate(req: Request, res: Response) {
    try {
      const { category, data } = req.body;

      if (!category) {
        return res.status(400).json({ error: 'category is required (PERFORMANCE or COLLEGE_NOTICE)', code: 'MISSING_CATEGORY' });
      }

      let formattedMessage = '';

      if (category === 'PERFORMANCE' || category === NotificationCategory.PERFORMANCE) {
        formattedMessage = NotificationTemplateService.generatePerformanceMessage(data || {});
      } else if (category === 'COLLEGE_NOTICE' || category === NotificationCategory.COLLEGE_NOTICE) {
        formattedMessage = NotificationTemplateService.generateCollegeNoticeMessage(data || {});
      } else {
        return res.status(400).json({ error: `Unsupported category: ${category}`, code: 'INVALID_CATEGORY' });
      }

      const charCount = formattedMessage.length;
      const estimatedSmsSegments = Math.ceil(charCount / 160) || 1;

      return res.status(200).json({
        category,
        message: formattedMessage,
        characterCount: charCount,
        estimatedSmsSegments
      });
    } catch (error: any) {
      console.error('Error previewing notification template:', error);
      return res.status(500).json({
        error: error.message || 'Failed to preview notification template',
        code: 'PREVIEW_TEMPLATE_ERROR'
      });
    }
  }

  /**
   * GET /api/admin/notifications/preview-student-performance/:studentId
   * Resolves student academic marks from DB and generates personalized parent performance update text.
   */
  static async previewStudentPerformance(req: Request, res: Response) {
    try {
      const studentId = req.params.studentId as string;
      if (!studentId) {
        return res.status(400).json({ error: 'studentId is required', code: 'MISSING_STUDENT_ID' });
      }

      const report = await AcademicPerformanceService.getStudentPerformanceFromDb(studentId);
      if (!report) {
        return res.status(404).json({ error: 'Student not found', code: 'STUDENT_NOT_FOUND' });
      }

      const student = await prisma.student.findUnique({
        where: { id: studentId },
        select: { parentName: true, parentMobile: true }
      });

      const message = NotificationTemplateService.generatePerformanceMessageFromReport(report);
      const charCount = message.length;
      const estimatedSmsSegments = Math.ceil(charCount / 160) || 1;

      return res.status(200).json({
        studentId,
        studentName: report.studentName,
        registerNumber: report.registerNumber,
        parentName: student?.parentName || 'Parent',
        parentMobile: student?.parentMobile || '',
        message,
        characterCount: charCount,
        estimatedSmsSegments,
        reportSummary: {
          percentage: report.percentage,
          ia1Percentage: report.ia1Percentage,
          ia2Percentage: report.ia2Percentage,
          improvement: report.improvement,
          progressionStatus: report.progressionStatus,
          performanceStatus: report.performanceStatus
        }
      });
    } catch (error: any) {
      console.error('Error previewing student performance message:', error);
      return res.status(500).json({
        error: error.message || 'Failed to preview student performance message',
        code: 'PREVIEW_STUDENT_PERFORMANCE_ERROR'
      });
    }
  }

  /**
   * GET /api/admin/notifications/templates/samples
   * Returns dictionary of all pre-formatted standard templates for both categories.
   */
  static async getSampleTemplates(_req: Request, res: Response) {
    try {
      const samples = NotificationTemplateService.getSampleTemplates();
      return res.status(200).json({ samples });
    } catch (error: any) {
      console.error('Error fetching sample templates:', error);
      return res.status(500).json({
        error: error.message || 'Failed to fetch sample templates',
        code: 'GET_SAMPLE_TEMPLATES_ERROR'
      });
    }
  }

  /**
   * POST /api/admin/notifications/send-performance
   * Dispatches Academic Performance notification to a student's parent via selected channels (SMS, WHATSAPP, BOTH).
   */
  static async sendPerformanceNotification(req: Request, res: Response) {
    try {
      const { studentId, channel = 'BOTH', simulateFailure = false } = req.body;

      if (!studentId) {
        return res.status(400).json({ error: 'studentId is required', code: 'MISSING_STUDENT_ID' });
      }

      const result = await NotificationService.dispatchPerformanceNotification({
        studentId,
        channel,
        simulateFailure
      });

      return res.status(200).json(result);
    } catch (error: any) {
      console.error('Error sending performance notification:', error);
      return res.status(500).json({
        error: error.message || 'Failed to dispatch performance notification',
        code: 'SEND_PERFORMANCE_NOTIFICATION_ERROR'
      });
    }
  }

  /**
   * POST /api/admin/notifications/send-section-performance
   * Dispatches Academic Performance notifications for all students in a section.
   */
  static async sendSectionPerformanceNotification(req: Request, res: Response) {
    try {
      const { sectionId, channel = 'BOTH', simulateFailure = false } = req.body;

      if (!sectionId) {
        return res.status(400).json({ error: 'sectionId is required', code: 'MISSING_SECTION_ID' });
      }

      const result = await NotificationService.dispatchSectionPerformanceNotifications({
        sectionId,
        channel,
        simulateFailure
      });

      return res.status(200).json(result);
    } catch (error: any) {
      console.error('Error sending section performance notifications:', error);
      return res.status(500).json({
        error: error.message || 'Failed to dispatch section performance notifications',
        code: 'SEND_SECTION_PERFORMANCE_ERROR'
      });
    }
  }

  /**
   * GET /api/admin/notifications/stats
   * Returns system-wide notification delivery metrics and queue status
   */
  static async getOverallQueueStats(_req: Request, res: Response) {
    try {
      const stats = await NotificationService.getOverallNotificationStats();
      return res.status(200).json({
        ...stats.databaseCounts,
        databaseCounts: stats.databaseCounts,
        queueStats: stats.queueStats
      });
    } catch (error: any) {
      return res.status(500).json({
        error: error.message || 'Failed to fetch notification stats',
        code: 'GET_QUEUE_STATS_ERROR'
      });
    }
  }

  /**
   * GET /api/admin/notifications/history
   * Retrieves paginated, multi-filtered Notification History with summary card metrics and masked parent mobile numbers.
   */
  static async getNotificationHistory(req: Request, res: Response) {
    try {
      const {
        academicYearId,
        departmentId,
        yearId,
        sectionId,
        type,
        category,
        status,
        date,
        startDate,
        endDate,
        search,
        page,
        limit
      } = req.query;

      const result = await NotificationService.getNotificationHistory({
        academicYearId: academicYearId as string,
        departmentId: departmentId as string,
        yearId: yearId as string,
        sectionId: sectionId as string,
        type: type as string,
        category: category as string,
        status: status as string,
        date: date as string,
        startDate: startDate as string,
        endDate: endDate as string,
        search: search as string,
        page: page ? Number(page) : undefined,
        limit: limit ? Number(limit) : undefined
      });

      return res.status(200).json(result);
    } catch (error: any) {
      console.error('Error fetching notification history:', error);
      return res.status(500).json({
        error: error.message || 'Failed to retrieve notification history',
        code: 'GET_NOTIFICATION_HISTORY_ERROR'
      });
    }
  }

  /**
   * POST /api/admin/notifications/:id/retry
   * Retries an individual FAILED notification.
   */
  static async retryNotification(req: Request, res: Response) {
    try {
      const id = req.params.id as string;
      if (!id) {
        return res.status(400).json({ error: 'Notification ID is required', code: 'MISSING_NOTIFICATION_ID' });
      }

      const result = await NotificationService.retryNotification(id);
      return res.status(200).json(result);
    } catch (error: any) {
      const status = error.message?.includes('Only notifications with FAILED status') ? 400 : 500;
      return res.status(status).json({
        error: error.message || 'Failed to retry notification',
        code: 'RETRY_NOTIFICATION_ERROR'
      });
    }
  }

  /**
   * POST /api/admin/notifications/retry-failed
   * Bulk retries failed notifications matching criteria.
   */
  static async bulkRetryFailedNotifications(req: Request, res: Response) {
    try {
      const { noticeId, category } = req.body;
      const result = await NotificationService.retryAllFailed({ noticeId, category });
      return res.status(200).json(result);
    } catch (error: any) {
      return res.status(500).json({
        error: error.message || 'Failed to bulk retry failed notifications',
        code: 'BULK_RETRY_ERROR'
      });
    }
  }
}
